@url = https://8080-fafasnevd-gamessw20111-uboidrxhb11.ws-us116.gitpod.io

GET {{{url}}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo" : "Vampire Survivors",
    "plataformas" : [
        {"id: 1"},
        {"id: 2"}
    ]
}


###
GET {{url}}/jogos/8