@url = https://8080-elisascaran-gamessw2202-3xa8w71pllp.ws-us116.gitpod.io

GET  {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json
 
{
    "nome": "Apple"
}

###
GET {{url}}/plataformas/2